### ISSUE TITLE
ms sql server on premises support

### ISSUE THREAD

**Issue by AlexOlap** [microsoft/dbt-fabric#105]
Hello!
Due these news about the future of the sqlserver-dbt adapter (https://github.com/dbt-msft/dbt-sqlserver/issues/441) can you have any plans about supporting sql server on premises (2019 or above) by dbt-fabric adapter?
Thks

**Comment by prdpsvs** [comment]
Hi @AlexOlap , We are considering this investment but can't promise anything.
Right now, fabric does not have complete T-SQL surface support for another adapter such as dbt-synapse or sqlserver-dbt adapter to take dependencies. After March 2024, we will revisit on this as new t-sql commands release in Fabric DW.

Note: Internally, we do want other MS SQL adapters to take dependency on dbt-fabric but its not there yet.
And to your question on on-prem sql 2019, it should be part of sqlserver dbt adapter. We do not have plans to create a new adapter for on-prem sql editions.

I am closing this issue at this time but please feel to create another issue if you have more questions
