### ISSUE TITLE
CTAS on Azure SQL

### ISSUE THREAD

**Issue by ms32035** [microsoft/dbt-fabric#114]
We're running our dbt projects agains Azure SQL database, and in order for models to work we had to modify
https://github.com/microsoft/dbt-fabric/blob/e8a59ed8a9167cc46d4a75819793aed48a9c038a/dbt/include/fabric/macros/materializations/models/table/create_table_as.sql#L27
by adding `WITH (DISTRIBUTION = ROUND_ROBIN)`

Not sure what the correct solution is for all favours of SQL on Azure so please advise and make necessary changes.

**Comment by prdpsvs** [comment]
@ms32035 , this adapter supports only Fabric DW. 
you need to dbt-synapse adapter for Azure Synapse Data Warehouse (Synapse Dedicated SQL Pool)
You need to use dbt-sqlserver for other flavors of Microsoft SQL.
