### ISSUE TITLE
Full refresh of seeds fails because the table doesn't get dropped first

### ISSUE THREAD

**Issue by natej-eb** [microsoft/dbt-fabric#128]
When using the `dbt seed --full-refresh` command or having `+full_refresh: true` in `dbt_project.yml`, the seed table doesn't get dropped first throwing this error: `[Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named '<seed_name>' in the database.` The `create table` command tries to run when the table already exists.

```
Running with dbt=1.7.8
Registered adapter: fabric=1.7.4
```

**Comment by prdpsvs** [comment]
@natej-eb , I tested it locally using Jaffle shop project. Please see the following screenshot. I tried the same steps you mentioned, and I can see that the tables are dropped from logs folder. I did `dbt seed & dbt seed --full-refresh` with and without following in dbt_project.yml file.
`seeds:
  jaffle_shop:
    +full_refresh: true
`
![image](https://github.com/microsoft/dbt-fabric/assets/19339281/520cd47e-eac7-4bb5-8024-6a7d31025ead)

**Comment by prdpsvs** [comment]
Screenshot of dbt logs from jaffle_shop project.
![image](https://github.com/microsoft/dbt-fabric/assets/19339281/85f78350-26ba-44b0-9c3c-49d8e819fd61)

**Comment by prdpsvs** [comment]
@natej-eb , I could not repro this error. Could you please repro and let me know?
