### ISSUE TITLE
Support nvarchar datatype

### ISSUE THREAD

**Issue by ericmuijsvanoord** [microsoft/dbt-fabric#132]
Currently nvarchar data type is not supported. For example adding a new nvarchar column to an existing snapshot, will create a nvarchar(1) as nvarchars are not recognized as text field> length is not taken into account.

**Comment by prdpsvs** [comment]
nvarchar is not supported by Fabric DW - https://learn.microsoft.com/en-us/fabric/data-warehouse/data-types#unsupported-data-types.

**Comment by ericmuijsvanoord** [comment]
Thanks @prdpsvs !
