### ISSUE TITLE
CTE's cause failure in snapshots

### ISSUE THREAD

**Issue by TonyUVC** [microsoft/dbt-fabric#135]
We are planning a migration from Postgres to Fabric or another cloud platform. A couple of the snapshots we use have CTE's in them for simple tasks like cross-referencing to an internal mapping table, cleaning up a string, or generating a date range.

These model's fail in Fabric with the following error:

[SQL Server]Incorrect syntax near the keyword 'WITH'. (156) (SQLMoreResults); [42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.

I have tested this with a very simple query:

select 'TEST' as sk,
CAST(GETDATE() as datetime2(6)) as updated_at

compared to:

WITH testdata as (
select 'TEST' as sk,
CAST(GETDATE() as datetime2(6)) as updated_at
)

select * from testdata

The first query works fine and the result is snapshot perfectly. As soon as it is wrapped in a CTE it fails with the previously identified error.

This can be worked around with the logic in the CTE's being pushed upstream, but our existing model in Postgres and the same model used while testing with Snowflake works fine and we would expect the same functionality to work in Fabric.

**Comment by prdpsvs** [comment]
@TonyUVC , Thanks for reporting the issue. I will look into this shortly.

**Comment by prdpsvs** [comment]
@TonyUVC , I addressed this today. I am going to give a patch release in a couple of days along other bug fixes. So please test v1.7.5 and let me know. Thanks for testing and keep passing the feedback.
