### ISSUE TITLE
Document What Incremental Strategies Are Supported

### ISSUE THREAD

**Issue by ernestoongaro** [microsoft/dbt-fabric#137]
Thanks to @victoriapm for reporting that MERGE does not work in Fabric yet. We need to know which incremental strategies are supported on Fabric today.

The default seems to be delete+insert. Which ones are supported and which ones are not? 

Definition of done:
1) We know which ones are supported
2) File Issues to give errors if trying one that isn't supported
3) Update the [table](https://docs.getdbt.com/docs/build/incremental-models#built-in-strategies) with fabric supported ones 
4) Update Fabric docs https://docs.getdbt.com/reference/resource-configs/fabric-configs

**Comment by prdpsvs** [comment]
@ernestoongaro , Let me do that. I may need a couple of weeks, but I will get to this.

**Comment by prdpsvs** [comment]
@ernestoongaro , Fabric currently support insert+delete. If unique key is not provided, it will default to append mode. I will update this in the documentation.

**Comment by ernestoongaro** [comment]
closed in https://github.com/dbt-labs/docs.getdbt.com/pull/5614 and https://github.com/dbt-labs/docs.getdbt.com/pull/5613
