### ISSUE TITLE
when I install dbt-fabric it mess up my dbt

### ISSUE THREAD

**Issue by virvirlopez** [microsoft/dbt-fabric#159]
Every command returns:

    from dbt.adapters.factory import adapter_management, register_adapter, get_adapter
ModuleNotFoundError: No module named 'dbt.adapters.factory'

**Comment by prdpsvs** [comment]
@virvirlopez , Can you share the version that you are installing?

**Comment by ahjulstad** [comment]
I stumbled on this issue with a similar error message. The error on my end was that I for some reason had changed the python environment in vscode.

**Comment by prdpsvs** [comment]
@virvirlopez , I am closing this issue for now. If you encounter, please feel free to re-open the issue
