### ISSUE TITLE
Constraint Name should be optional and generate a unique name

### ISSUE THREAD

**Issue by bebemn** [microsoft/dbt-fabric#186]
The [documentation for constraints in dbt](https://docs.getdbt.com/reference/resource-properties/constraints) specifies that the name property is optional. If the name is left out of the definition dbt-fabric throws the following exception.
```
Database Error in model model1 (models\gold\datamart1\dimensions\table1.sql)
Constraint name cannot be empty. Provide constraint name  - column column1_hk and run the project again.
compiled Code at target\run\project1\models\gold\datamart1\dimensions\table1.sql
```
This was more of a problem when Fabric Data Warehouse prohibited using the same constraint name on multiple objects. This limitation appears to have been removed, at least in regard to tables in different schemas. However, it does not follow the standard and users changing platforms may have issue with this.

**Comment by prdpsvs** [comment]
@bebemn , good point, let me take a look into this.

**Comment by prdpsvs** [comment]
@bebemn , I am closing this issue because of DW limitation. This behavior is inherited from other Microsoft SQL engines, which won't be possible. 

Please create a new issue to propose a good naming convention for a constraint.
