### ISSUE TITLE
Handling __dbt_tmp tables in incremental models

### ISSUE THREAD

**Issue by yaragheb** [microsoft/dbt-fabric#188]
When I run an incremental model in an incremental run, dbt is creating `__dbt_tmp` tables and never cleaning them up.

In the SQL file:

```
{{
    config(
        materialized = "incremental",
    )
}}
```

**Warehouse:**

![image](https://github.com/microsoft/dbt-fabric/assets/37471568/fdb3791f-7680-4dca-bef1-98a070590afe)

**Comment by prdpsvs** [comment]
@yaragheb , which version of the adapter are you using?

**Comment by yaragheb** [comment]
@prdpsvs dbt-fabric==1.7.4

**Comment by AlessandroLollo** [comment]
Same for me with `dbt-fabric==1.8.6`
