### ISSUE TITLE
Python models?

### ISSUE THREAD

**Issue by joegood** [microsoft/dbt-fabric#190]
Are there any plans to support Python models with this adapter?

When I try to use one now, I get the following error:
Materialization "materialization_table_fabric" only supports languages ['sql']; got "python"

**Comment by prdpsvs** [comment]
@joegood , no, we do not plan to support python models because DW adapter supports T-SQL surface area.

**Comment by joegood** [comment]
What? Do you know what the Python models are used for? This means you're blocking the entire Python AI/ML module base on MS servers.

**Comment by lehmus** [comment]
Python is "the second language of DBT" and has been available for BigQuery, Databricks and Snowflake for two years. Why would MS Fabric leave it out?
https://www.getdbt.com/blog/introducing-support-for-python

How would one use T-SQL to create ML training and evaluation workloads? We use Python for many tasks, including data engineering, and would like to manage the Python workloads with DBT as well. I have understood that DBT will be integrated with Fabric increasingly in the future, so I would expect Fabric to support basic functionalities of DBT like Python models.

**Comment by boxysean** [comment]
I am working with a team interested in dbt python on Fabric, and found the [microsoft/dbt-fabricspark](https://github.com/microsoft/dbt-fabricspark) project. I wanted to link it here in case others also were searching.
