### ISSUE TITLE
Incorrect result set from the Table in Fabric Warehouse

### ISSUE THREAD

**Issue by SharmaRakeshPFE** [microsoft/dbt-fabric#218]
While working on the Fabric Portal I noticed different result set from the table. For an example the query is resulting columns from a different table which was not even referenced.

Table referenced in the query is EMP_FLAT_TBL but the result returned is from different table (EMP). This behavior was noticed multiple times in query and even in function. 

SELECT * FROM EMP_FLAT_TBL where Id='V59OF92YF627HFY0'
SELECT * FROM EMP_FLAT_TBL where Id is NULL

CREATE FUNCTION dbo.fn_return_bio(@id varchar(50))
RETURNS TABLE
AS
RETURN
(
SELECT JSON_VALUE(JDETAILS, '$.bio') as 'Bio'
FROM  EMPJSON1 
WHERE JSON_VALUE(JDETAILS, '$.id') ='ENTOCR13RSCLZ6KU'
)

SELECT * FROM dbo.fn_return_bio('ENTOCR13RSCLZ6KU');

<img width="1127" alt="Error_1" src="https://github.com/user-attachments/assets/fcc5ddeb-ea6b-463a-b37a-8c9c00ab7d23">
<img width="1159" alt="Error_2" src="https://github.com/user-attachments/assets/62be9f38-d73d-4a55-80d2-af88d2f048c9">
<img width="1150" alt="Error_3" src="https://github.com/user-attachments/assets/1443c0f2-1c86-4ccc-868e-c2bf83bf88e7">

**Comment by prdpsvs** [comment]
@SharmaRakeshPFE , How is this issue related to dbt-fabric adapter. You need open a ticket with Microsoft Support. If this is related to dbt-fabric adapter, please re-open the issue with information to repro the errror/issue.
