### ISSUE TITLE
Committed changes created by dbt fail to update with Fabric workspace git.

### ISSUE THREAD

**Issue by timdenouden** [microsoft/dbt-fabric#231]
## Description
When an existing dbt project is run against a Fabric warehouse in a git enabled workspace. Any models using the `ref()` macro will fail to update in a separate Warehouse when attempting to update via git. This appears to be due to the three part naming for models that exist in the Warehouse being unable to be found by the Fabric workspace git merge system.  I am unsure if this issue is a problem with the Fabric git merge system or with this library issuing the 3 part names for intra Warehouse references (I expect this depends on intended functionality in Fabric).

We have found a workaround by overriding the `ref` macro with:
```jinja
{# macros/ref.sql #}

{% macro ref(model_name) %}

    {% do return(builtins.ref(model_name).include(database=false)) %}

{% endmacro %}
```
This works by removing the database name (The name of the Warehouse) which appears to confuse the Warehouse project git merge.
 
## Steps to recreate:
1. Create a new empty warehouse (A) artifact in a Fabric workspace connected to git.
2. Target and run a dbt project with views that reference other entities within the warehouse.
3. Commit the new Warehouse changes to your branch in Workspace A
4. In a separate Workspace (B), link the same branch and attempt to update from the branch based on Workspace A
5. An error will appear saying the view with the references cannot find the source objects as they don't exist.

**Comment by dataders** [comment]
yo @timdenouden -- what's good!

I haven't looked too much into the issue here, just wanted to call out that there's still a gap in suport within SQL for three-part names for some commands. In those cases it's required to execute a `USE {DATABSE};` statement first. Maybe something like that is going on?

@prdpsvs can share more here, but check out #161 and #166 for examples.

**Comment by prdpsvs** [comment]
Hey @timdenouden , a question and suggestion.

- Why do you maintain and link same branch with two different workspaces? This is not widely used pattern and have un-intended consequences when you try to apply git changes to workspace using "Update All" button.
- Do workspace B DW item has references within the warehouse? If not, you need to run the dbt project targeting DW in Workspace B and then try to link the branch.

@dataders , if three-part naming is a problem, then the same problem must occur in Workspace A considering the name of the warehouse is same.

**Comment by prdpsvs** [comment]
@timdenouden , do let me know if you still want to connect. I am closing this for now as this is not related to adapter. We can start a new conversation about this though
