### ISSUE TITLE
dbt job failing - TCP Provider: Error code 0x68 (104)

### ISSUE THREAD

**Issue by frerus** [microsoft/dbt-fabric#245]
Hi!

We are using dbt cloud and Fabric, and are experiencing some jobs failing with the following error:
('08S01', '[08S01] [Microsoft][ODBC Driver 18 for SQL Server]TCP Provider: Error code 0x68 (104) (SQLExecDirectW)')

The jobs usually runs the next time or if we trigger them manually.

So we are expecting this to be some sort of connectivity / or error related to the warehouse in Fabric.
We have set up retries on the connection in dbt cloud, and we would expect it to retry it if the error is recoverable.

Is it possible to recover from this error - and retry?
Or is there another workaround to avoid this issue?

**Comment by prdpsvs** [comment]
Okay, how long are you running your job?
0x68 is 104 in decimal, and that is a Connection Reset by Peer error (i.e. the server abruptly closed the connection). This issue happens you when the connection using proxy policy (by default all connections in Fabric DW are proxy.

Couple of options to mitigate this issue

- Enable connection pooling, it should be enabled by default. I am explicitly enabling connection pooling in v1.8.9
- Can you set retries to 3 in profiles.yml file and see if this issue occurs again? The ConnectRetryCount value is derived from retries in profiles.yml. I am setting a default value for retries as 3 just in case.

Please try and let me know if you are still facing this issue.

**Comment by frerus** [comment]
Thanks for the feedback!

I haven't encountered the error in a while now, so it looks to be better now. 
We did reduce the thread concurrency down to 2 - and also increased the retry attempts to 5 (not in the profiles.yml but under the connection in dbt cloud)

The job is not running very long, maybe 1-2 minutes tops. 
I see that our dbt cloud still seem to be running the v1.8.8 (From the connection string; 
";TrustServerCertificate=No;APP=dbt-fabric/1.8.8post1+xyz;ConnectRetryCount=5".
