### ISSUE TITLE
FabricConnectionManager does not handle non-standard ports

### ISSUE THREAD

**Issue by rlshuhart** [microsoft/dbt-fabric#247]
It appears dbt-sqlserver uses FabricConnectionManager for Windows Login authentication, however, FabricConnectionManager does not make use of port in credentials object, therefore, non-standard port are ignored in the adapter configuration. Please refer to https://github.com/dbt-msft/dbt-sqlserver/issues/496

**Comment by prdpsvs** [comment]
TDS operates on TCP port 1433 and customers have no control over the port in Fabric DW. 
Have you tried to provide the port number as part of the host/server in your profiles.yml file?

I believe, SQL Server adapter must expand credentials to include port number. I am not planning to add port configuration to Fabric adapter.

**Comment by rlshuhart** [comment]
@prdpsvs, that makes sense and thank you for considering the issue.
