### ISSUE TITLE
Catalog Information Only Works for Primary Database

### ISSUE THREAD

**Issue by peterallenwebb** [microsoft/dbt-fabric#249]
Hello, I am a maintainer of dbt-core. I'd like to pass along an issue raised by one of our users.

The user is invoking `dbt docs generate`, which writes catalog information to `target/catalog.json` upon completion. Their project uses multiple databases, but they noticed that the catalog information only includes information about objects in the database specified in their profile. The expected behavior is that all objects dbt is aware of should be present in the catalog.json file, even if they are in a secondary database.

I traced the issue to [dbt-fabric's implementation of the get_catalog() macro](https://github.com/microsoft/dbt-fabric/blob/525fe95c960beb3c8dc0b34130111d6284aa3eab/dbt/include/fabric/macros/adapters/catalog.sql#L1C10-L1C29). Note that this implementation will always use the primary database.

**Comment by prdpsvs** [comment]
@peterallenwebb , the catalog macro does not have context in which database it is running. Is there a way to pass on that context so that I can set it in the catalog macro?

**Comment by prdpsvs** [comment]
@peterallenwebb , Addressed this issue in in V1.8.9. Please re-open if you still see any challenges
