### ISSUE TITLE
"dbt debug" succeeds but "dbt run" fails

### ISSUE THREAD

**Issue by jhoolachan** [microsoft/dbt-fabric#38]
I'm trying to test this adapter using the sample jaffle_shop project. All checks pass when running "dbt debug" but "dbt run" fails with:

`('HY000', "[HY000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Exception occurred while reading infrastructure server's response.Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.\r\nAn existing connection was forcibly closed by the remote host\r\n Current Activity Id: e8ecb8f7-1936-47e2-a89f-968b3438a997 (4014) (SQLExecDirectW)")
`

I've tried the CLI and Interactive authentication methods and am running:

- OBDC Driver 17/18 (tried both)
- dbt=1.4.6

Please let me know if you need more details. Thanks!

![dbt-debug](https://github.com/microsoft/dbt-fabric/assets/9311394/4e3e8be9-c068-4474-908f-442fcfc86990)
![dbt-run](https://github.com/microsoft/dbt-fabric/assets/9311394/6934c2be-8d81-420e-b8f3-4ebc92011712)

**Comment by prdpsvs** [comment]
@jhoolachan , could you share the dbt log file? It may contain more information about the actual issue. Fabric DW engineering team is still working through throwing right exceptions.

**Comment by thebroberts** [comment]
I hit this issue as well a few weeks ago. It's the comments in the `.sql` files causing the issue. After I removed them I was able to `dbt run` successfully.

**Comment by jhoolachan** [comment]
I am unfortunately running into issues uploading/pasting logs due to company security measures.

One issue is that the adapter seems to wrap the SQL statements within EXEC(), but the final ");" is placed as the last characters of the last line (see below). In the scenario below, the ");" ends up being commented out so maybe it would be better if the final ");" was placed on its own line below everything else.

```
    EXEC('create view "dbo"."my_first_dbt_model__dbt_tmp_temp_view" as /*
    Welcome to your first dbt model!
    Did you know that you can also configure models directly within SQL files?
    This will override configurations stated in dbt_project.yml

    Try changing "table" to "view" below
*/


with source_data as (

    select 1 as id
    union all
    select null as id

)

select *
from source_data

/*
    Uncomment the line below to remove records with null `id` values
*/

-- where id is not null;');
```

Even if I fix the erros above and remove all the comments per @thebroberts, "dbt run" still fails on the CREATE TABLE step below. Both the CREATE VIEW and DROP VIEW statements run fine when copy/pasted into the DWH SQL editor and executed but create table fails with the transport error.

```
EXEC('create view "dbo"."my_first_dbt_model__dbt_tmp_temp_view" as

with source_data as (

    select 1 as id
    union all
    select null as id

)

select *
from source_data;');


EXEC('CREATE TABLE "dbo"."my_first_dbt_model__dbt_tmp" AS (SELECT * FROM "dbo"."my_first_dbt_model__dbt_tmp_temp_view");');

EXEC('DROP view IF EXISTS "dbo"."my_first_dbt_model__dbt_tmp_temp_view";');
```

**Comment by thebroberts** [comment]
Apologies for responding from memory... I've set up my env again. I am able to run the sample if I change the materialization to `view`. If I use `table`, it fails.

**Comment by prdpsvs** [comment]
@jhoolachan, note that there is a known issue with Fabric DW. CTAS is not supported on a view backed by a table. As a workaround, please replace `select 1 as id union all select null as id` with actual table in the view definition and dbt run should succeed.

**Comment by jhoolachan** [comment]
Hi @prdpsvs - I’m not sure I’m following. As far as I know, everything besides…

`with source_data as (

    select 1 as id
    union all
    select null as id

)

select *
from source_data;');
`

…is added by the adapter. How can I can the the code you reference? And would you mind pasting that portion in your reply?

**Comment by prdpsvs** [comment]
@jhoolachan, Currently, Fabric DW can't do a CTAS on a VIEW 

`CREATE VIEW [view name] AS
select 1 as id
union all
select null as id`

`CREATE TABLE [Table Name] AS SELECT * FROM [view name]` does not work if view is not selecting data from a table.

You need to change the source of your view to actual table in the model file (may be by using seeds)

**Comment by jhoolachan** [comment]
@prdpsvs - I've confirmed the seed approach works.

The original code came from a dbt-provided tutorial/code below (`dbt init jaffle_shop`) so hopefully others will see this and/or the CTAS on a view is resolved soon.

[Tutorial](https://docs.getdbt.com/quickstarts/manual-install?step=2)

Thanks!
