### ISSUE TITLE
dbt-utils support

### ISSUE THREAD

**Issue by prdpsvs** [microsoft/dbt-fabric#42]
Support dbt-utils

**Comment by johalnes** [comment]
Hi! Are there any updates on support for dbt-utils?

**Comment by SaintofSpadesSOA** [comment]
Are there any updates for support on dbt-utils?

**Comment by LoHertel** [comment]
> Are there any updates for support on dbt-utils?

@prdpsvs has already added some utils macros:  https://github.com/microsoft/dbt-fabric/tree/main/dbt/include/fabric/macros/utils
Do you need an utils macro, which doesn't work yet?

**Comment by prdpsvs** [comment]
@johalnes, @SaintofSpadesSOA , I am closing this issue as Fabric support utils function. Please let me know if specific util functions are missing.
