### ISSUE TITLE
use driver's built-in support for ActiveDirectoryServicePrincipal rather than fetching token with `azure-identity`

### ISSUE THREAD

**Issue by dataders** [microsoft/dbt-fabric#76]
Right now `authentication=serviceprincipal` will use `azure.identity` to fetch a token, then pass the token as an extra option. This is unnecessary, and only was implemented in the first place as a workaround for authenticating to Azure SQL in older driver versions. The driver's built-in method should be used instead.

**Comment by prdpsvs** [comment]
Addressed in https://github.com/microsoft/dbt-fabric/tree/v1.6.latest
