### ISSUE TITLE
Stability of this adapter

### ISSUE THREAD

**Issue by namur007** [microsoft/dbt-fabric#86]
Hello, 

Can one of the maintainers comment on the status of this adapter with respect to building off its work? My team would like to use the sql server adapter, but its been indicated that will come as a downstream of this. 

Given the lack of discussion and activity on the dbt-mssql repo, we would like to understand if the status of this adapter means we can build from it to update the existing adapter.

**Comment by prdpsvs** [comment]
@namur007, we plan to release updates to this adapter in the future.
As you see, dbt 1.7 is already released. We are addressing a few bugs + table clone feature in dbt 1.6.1 and should be released in a couple of weeks.
