### ISSUE TITLE
simplify now that `sp_rename` is supported

### ISSUE THREAD

**Issue by dataders** [microsoft/dbt-fabric#91]
now that `sp_rename` is supported in Fabric ([announcement blog](https://blog.fabric.microsoft.com/en-us/blog/announcing-fabric-warehouse-support-for-sp_rename/)), we can use it to simplify both
- `rename_relation` 
- `alter_column_type`

for `rename_relation`, the [sqlserver version](https://github.com/dbt-msft/dbt-sqlserver/blob/9546c40044c82c46cdd3383fc14448a0d28d405a/dbt/include/sqlserver/macros/adapters/relation.sql#L53-L63) now, right? it's 10 lines compared to dbt-fabric's 100?

https://github.com/microsoft/dbt-fabric/blob/5a963b59ecfbb8367221fc73830bd1e66abe0fdb/dbt/include/fabric/macros/adapters/relation.sql#L51-L153

https://github.com/microsoft/dbt-fabric/blob/5a963b59ecfbb8367221fc73830bd1e66abe0fdb/dbt/include/fabric/macros/adapters/columns.sql#L55-L116

**Comment by prdpsvs** [comment]
@dataders , the work for table rename is already done with v1.6.1. Should be released by end of this week. sp_rename for columns are not supported yet. ![image](https://github.com/microsoft/dbt-fabric/assets/19339281/a6079950-17db-4aec-a1ed-7fab484819d3)
