### ISSUE TITLE
update SQL statement logging 

### ISSUE THREAD

**Issue by dataders** [microsoft/dbt-fabric#97]
dbt Cloud relies on a newer convention, `FireEvent` to display compiled SQL in the logs. See https://github.com/dbt-labs/dbt-core/pull/6325 and [`connections.py#L58-L64`](https://github.com/dbt-labs/dbt-core/blame/81236a3dca040c80ed0cb1ee6e125eace92f7e64/core/dbt/adapters/sql/connections.py#L58-L64)

```py
        fire_event(
            ConnectionUsed(
                conn_type=self.TYPE,
                conn_name=cast_to_str(connection.name),
                node_info=get_node_info(),
            )
        )
```

**Comment by prdpsvs** [comment]
@dataders , I addressed this issue in 1.7.1
