### ISSUE TITLE
1.6.1 Removes Auth methods

### ISSUE THREAD

**Issue by colin-rogers-dbt** [microsoft/dbt-fabric#99]
This [change](https://github.com/microsoft/dbt-fabric/commit/cf3688073d41ee70463f0717c892c3cc27a08abe#diff-c1b0256b44c042e86c431c5151b6c0812c05e8c047c1d4f9b12b0b9538cbdb55L12) removed authentication method that dbt Cloud relies on, specifically: `ClientSecretCredential`

Can we revert and include those?

**Comment by prdpsvs** [comment]
@colin-rogers-dbt , Addressed this issue in 1.6.2 and 1.7.1 + versions.
released -> 1.6.2 just now. https://pypi.org/project/dbt-fabric/1.6.2/


I did not revert the change, rather, I added service principal as an alias to ActiveDirectoryServicePrincipal authentication mode.
Allowing users to provide "ServicePrincipal" as an authentication mode. Adapter will treat ServicePrincipal as ActiveDirectoryServicePrincipal authentication mode.
